import { NextResponse } from "next/server";
import { getCurrentUser, hasRole } from "@/lib/auth";
import { recordRedcapActivity } from "@/lib/redcap-activity";
import { validateFields } from "@/lib/redcap-validation";
import { completeQueueEntry } from "@/lib/clinic-queue";
import { generateUic } from "@/lib/uic";

const REDCAP_API_URL = process.env.REDCAP_API_URL;
const REDCAP_API_TOKEN = process.env.REDCAP_API_TOKEN;
type Values = Record<string, string>;
type Submission = { mode?: unknown; recordId?: unknown; enrollment?: unknown; clinicEnrollment?: unknown; clientStatus?: unknown; profile?: unknown; visit?: unknown; prepVisit?: unknown; monitoring?: unknown; includeClinicEnrollment?: unknown; includeClientStatus?: unknown; includeProfile?: unknown; includePrepVisit?: unknown; includeMonitoring?: unknown; queueId?: unknown };

const enrollmentFields = ["ce_active","ce_vital_status","ce_date","ce_implementing_partner","ce_district","ce_hotspot","ce_outreach_worker","ce_patient_code","ce_nid","ce_nationality","ce_last_name","ce_first_name","ce_middle_name_1","ce_middle_name_2","ce_middle_name_3","ce_alias","ce_dob","ce_gender_identity","ce_mobility","ce_vision","ce_kp_type","ce_tel_primary","ce_contact_address"];
const clientStatusFields = ["ce_active","ce_vital_status","ce_exit_date","ce_exit_reason"];
const clinicEnrollmentFields = ["cne_date","cne_facility","cne_district","cne_supervisor","cne_worker","cne_prev_visit_6m","cne_prev_center","cne_outreach_contact","cne_age_first_sex","cne_sex_3m","cne_partners_1w","cne_msm_sex_type","cne_sex_exchange","cne_sw_start_age","cne_sw_paid_week","cne_sw_unpaid_week","cne_condom_24h","cne_condom_1m","cne_lube_1m","cne_alcohol_1m","cne_drug_ever","cne_drug_1m","cne_drug_1w","cne_injected_3m","cne_inject_24h","cne_inject_1w","cne_share_needle_24h","cne_share_needle_1w","cne_sti_symp_6m","cne_sti_treat_location","cne_pregnancies","cne_pregnant_now","cne_antenatal","cne_num_children","cne_contraception_type","cne_violence_3m","cne_violence_type","cne_violence_help","cne_hiv_prev_test","cne_hiv_prev_test_since","cne_hiv_prev_result","cne_hiv_prev_result_disclosed","cne_hiv_prev_treat","cne_hiv_prev_treat_since","cne_hiv_prev_treat_facility","cne_contact_ok","cne_peer_contact_ok","cne_comorbidities","cne_comorbidity_other","cne_notes"];
const profileFields = ["htp_effective_date","htp_care_status","htp_care_facility","htp_care_status_other","htp_change_reason","htp_diagnosis_date","htp_prev_ltfu","htp_art_reg_date","htp_art_reg_place","htp_started_abroad","htp_art_start_date","htp_art_regimen","htp_art_regimen_other","htp_additional_medications","htp_art_adherence","htp_notes"];
const visitFields = ["cnv_worker","cnv_date","cnv_is_new_client","cnv_reason","cnv_reason_other","cnv_complaints","cnv_referred_by","cnv_exam_done","cnv_exam_findings","cnv_medication_supplied","cnv_other_med_supplied","cnv_art_prescription_months","cnv_no_medication_reason","cnv_next_blood_test","cnv_next_doctor_review","cnv_next_med_collection","cnv_blood_collected","cnv_hiv_reported","cnv_hiv_lab_test_done","cnv_hiv_lab_test_date","cnv_hiv_lab_result_received","cnv_hiv_lab_result","cnv_hbv_reported","cnv_hbv_lab_test_done","cnv_hbv_lab_test_date","cnv_hbv_lab_result_received","cnv_hbv_lab_result","cnv_hbv_treat","cnv_hbv_vaccination_status","cnv_hcv_reported","cnv_hcv_lab_test_done","cnv_hcv_lab_test_date","cnv_hcv_lab_result_received","cnv_hcv_lab_result","cnv_hcv_vl_date","cnv_hcv_vl_result","cnv_hcv_treat","cnv_syp_reported","cnv_syp_lab_test_done","cnv_syp_lab_test_date","cnv_syp_lab_result_received","cnv_syp_lab_result","cnv_syphilis_referral","cnv_syphilis_refer_where","cnv_sti_syndrome","cnv_sti_screened","cnv_sti_treatment","cnv_sti_treated","cnv_fp_counselling","cnv_post_abortion","cnv_risk_reduction","cnv_condom_demo","cnv_num_male_condoms","cnv_num_female_condoms","cnv_num_lube","cnv_num_hiv_selftest_kits","cnv_num_needles","cnv_gbv_screen","cnv_gbv_treat","cl_gbv_refer","cnv_gbv_refer_where","cnv_alcohol_screen","cnv_alcohol_treat","cnv_alcohol_refer","cnv_alcohol_refer_where","cnv_ost_screen","cnv_ost_treat","cnv_ost_refer","cnv_ost_refer_where","cnv_cervical_screen","cnv_cervical_treat","cnv_cervical_refer","cnv_cervical_refer_where","cnv_abscess_screen","cnv_abscess_treat","cnv_abscess_refer","cnv_abscess_refer_where","cnv_other_screen","cnv_other_treat","cnv_other_refer","cnv_other_refer_where","cnv_lab_ref","cnv_lab_tests","cnv_lab_location","cnv_other_fac_ref","cnv_other_facility","cnv_comments","cnv_next_appt","cnv_next_reason"];
const prepVisitFields = ["pv_visit_date","pv_visit_purpose","pv_recorded_by","pv_next_appointment_date","pv_followup_stage","pv_blood_draw_date","pv_tests_collected","pv_other_test_collected","pv_sample_reference","pv_blood_draw_notes","pv_hiv_result","pv_syphilis_result","pv_creatinine_result","pv_hbsag_result","pv_hcv_result","pv_sti_reported","pv_side_effects","pv_medication","pv_other_medication","pv_lot_number","pv_medication_dispensed","pv_prescription_months","pv_next_collection_date","pv_no_medication_reason","pv_physician","pv_physician_comments","pv_blood_test_date","pv_doctor_review_date","pv_syphilis_referral","pv_hcv_referral","pv_hbv_vaccination_status","pv_other_referral","pv_status_at_visit","pv_profile_updated"];
const monitoringFields = ["htm_date","htm_is_baseline","htm_art_status","htm_cd4_date","htm_cd4_level","htm_vl_date","htm_viral_load_detectable","htm_vl_level","htm_notes"];

function values(value: unknown): Values | null { if (!value || typeof value !== "object" || Array.isArray(value)) return null; const entries = Object.entries(value); return entries.every(([, item]) => typeof item === "string") ? Object.fromEntries(entries) as Values : null; }
const checkboxFields = ["ce_kp_type","cne_msm_sex_type","cne_sti_symp_6m","cne_sti_treat_location","cne_contraception_type","cne_violence_type","cne_comorbidities","htp_art_regimen","cnv_reason","cnv_medication_supplied","cnv_sti_syndrome","cnv_lab_tests","pv_visit_purpose","pv_tests_collected"];
function copyAllowed(source: Values, allowed: string[]) { const row:Values={}; for(const key of allowed)if(source[key]!==undefined&&source[key]!=="")row[key]=source[key].trim(); for(const key of checkboxFields){if(!allowed.includes(key)||!source[key])continue;for(const code of source[key].split(",").filter(item=>/^\d+$/.test(item)))row[`${key}___${code}`]="1";delete row[key];} return row; }
async function redcap(params: Record<string,string>) { if(!REDCAP_API_URL||!REDCAP_API_TOKEN)throw new Error("REDCap API configuration is missing."); const response=await fetch(REDCAP_API_URL,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({token:REDCAP_API_TOKEN,...params}),cache:"no-store"}); const text=await response.text();let result:unknown=text;try{result=JSON.parse(text)}catch{}if(!response.ok||(result&&typeof result==="object"&&"error" in result))throw new Error(result&&typeof result==="object"&&"error" in result?String((result as {error:unknown}).error):text||`REDCap returned HTTP ${response.status}.`);return result; }
async function exportRecord(recordId:string){const result=await redcap({content:"record",action:"export",format:"json",type:"flat",rawOrLabel:"raw",rawOrLabelHeaders:"raw",returnFormat:"json","records[0]":recordId,"forms[0]":"client_enrollment","forms[1]":"hiv_treatment_profile","forms[2]":"clinic_visit","forms[3]":"hiv_clinical_monitoring","forms[4]":"prep_visit"});return Array.isArray(result)?result as Values[]:[];}
function latestProfile(rows:Values[]){const profiles=rows.filter(row=>row.redcap_repeat_instrument==="hiv_treatment_profile").sort((a,b)=>Number(b.redcap_repeat_instance||0)-Number(a.redcap_repeat_instance||0));const latest=profiles[0];return latest?Object.fromEntries(profileFields.map(field=>[field,latest[field]??""])):null;}

function hasClinicEnrollment(rows:Values[]){return rows.some(row=>clinicEnrollmentFields.some(field=>Boolean(row[field]?.trim()))||["1","2"].includes(row.clinic_enrollment_complete?.trim()??""));}
export async function GET(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Authentication required."},{status:401});if(!hasRole(user,"HEALTHCARE_ASSISTANT"))return NextResponse.json({error:"Healthcare Assistant access is required."},{status:403});const uic=new URL(request.url).searchParams.get("uic")?.trim().toUpperCase()??"";if(!uic)return NextResponse.json({error:"A UIC is required."},{status:400});try{const rows=await exportRecord(uic),main=rows.find(row=>!row.redcap_repeat_instrument);return NextResponse.json({exists:rows.some(row=>row.uic_ori===uic),hasClinicEnrollment:hasClinicEnrollment(rows),clientStatus:main?Object.fromEntries(clientStatusFields.map(field=>[field,main[field]??""])):null,latestProfile:latestProfile(rows)});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to load the client from REDCap."},{status:502});}}

export async function POST(request:Request){
  const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Authentication required."},{status:401});if(!hasRole(user,"HEALTHCARE_ASSISTANT"))return NextResponse.json({error:"Healthcare Assistant access is required."},{status:403});
  let input:Submission;try{input=await request.json() as Submission}catch{return NextResponse.json({error:"The request body must be valid JSON."},{status:400})}
  const mode=input.mode,recordId=typeof input.recordId==="string"?input.recordId.trim().toUpperCase():"",enrollment=values(input.enrollment),clinicEnrollment=values(input.clinicEnrollment),clientStatus=values(input.clientStatus),profile=values(input.profile),visit=values(input.visit),prepVisit=values(input.prepVisit),monitoring=values(input.monitoring);const includeClinicEnrollment=mode==="new"||input.includeClinicEnrollment===true,includeClientStatus=input.includeClientStatus===true,includeProfile=mode==="new"||input.includeProfile===true,includePrepVisit=input.includePrepVisit===true,includeMonitoring=input.includeMonitoring===true;
  if((mode!=="new"&&mode!=="existing")||!recordId||!visit||(includeClinicEnrollment&&!clinicEnrollment)||(includeClientStatus&&!clientStatus)||(includeProfile&&!profile)||(includePrepVisit&&!prepVisit)||(includeMonitoring&&!monitoring))return NextResponse.json({error:"Invalid Clinic workflow submission."},{status:400});
  visit.cnv_is_new_client=mode==="new"?"1":"0";
  if(!visit.cnv_worker||!visit.cnv_date||!visit.cnv_reason)return NextResponse.json({error:"Clinic worker, visit date, and reason for visit are required."},{status:400});
  if(includePrepVisit&&(!prepVisit?.pv_visit_date||!prepVisit.pv_visit_purpose||!prepVisit.pv_recorded_by))return NextResponse.json({error:"PrEP visit date, purpose, and recorded by are required when PrEP is selected."},{status:400});
  if(includePrepVisit&&prepVisit){const purposes=new Set(prepVisit.pv_visit_purpose.split(","));if(purposes.has("1")&&(!prepVisit.pv_blood_draw_date||!prepVisit.pv_tests_collected))return NextResponse.json({error:"PrEP blood draw date and tests collected are required."},{status:400});if(purposes.has("2")&&(!prepVisit.pv_doctor_review_date||!prepVisit.pv_physician))return NextResponse.json({error:"PrEP doctor review date and physician are required."},{status:400});if(purposes.has("3")&&!prepVisit.pv_medication_dispensed&&!prepVisit.pv_no_medication_reason)return NextResponse.json({error:"Enter PrEP medication dispensed or the reason no medication was supplied."},{status:400});prepVisit.pv_profile_updated="0";}
  if(visit.cnv_hiv_lab_test_done==="1"&&!visit.cnv_hiv_lab_test_date)return NextResponse.json({error:"HIV laboratory test date is required when an HIV laboratory test was performed."},{status:400});
  if(mode==="new"){const required=["ce_date","ce_district","ce_hotspot","ce_outreach_worker","ce_last_name","ce_first_name","ce_dob","ce_gender_identity","ce_kp_type"];if(!enrollment||!required.every(key=>enrollment[key]?.trim()))return NextResponse.json({error:"Complete all required enrollment fields."},{status:400});if(generateUic(enrollment)!==recordId)return NextResponse.json({error:"The generated UIC does not match the enrollment details."},{status:400});}
  if(includeClinicEnrollment&&!clinicEnrollment?.cne_date)return NextResponse.json({error:"Clinic enrollment date is required."},{status:400});
  if(includeProfile&&(!profile?.htp_effective_date||!profile.htp_care_status||!profile.htp_art_start_date))return NextResponse.json({error:"Profile effective date, care status, and ART start date are required for a treatment profile."},{status:400});
  if(includeMonitoring&&!monitoring?.htm_date)return NextResponse.json({error:"Monitoring date is required when adding clinical monitoring."},{status:400});
  if(includeClientStatus&&clientStatus?.ce_vital_status==="2"&&(!clientStatus.ce_exit_date||clientStatus.ce_active!=="0"))return NextResponse.json({error:"A deceased client requires an exit date and inactive status."},{status:400});
  const validationError=(mode==="new"&&enrollment?validateFields(enrollment,enrollmentFields):null)||(includeClinicEnrollment&&clinicEnrollment?validateFields(clinicEnrollment,clinicEnrollmentFields):null)||(includeClientStatus&&clientStatus?validateFields(clientStatus,clientStatusFields):null)||(includeProfile&&profile?validateFields(profile,profileFields):null)||validateFields(visit,visitFields)||(includePrepVisit&&prepVisit?validateFields(prepVisit,prepVisitFields):null)||(includeMonitoring&&monitoring?validateFields(monitoring,monitoringFields):null);if(validationError)return NextResponse.json({error:validationError},{status:400});
  try{
    const existing=await exportRecord(recordId),exists=existing.some(row=>row.uic_ori===recordId);if(mode==="new"&&exists)return NextResponse.json({error:`UIC ${recordId} already exists. Use Existing client.`},{status:409});if(mode==="existing"&&!exists)return NextResponse.json({error:"The selected client no longer exists in REDCap."},{status:409});if(mode==="existing"&&includeClinicEnrollment&&hasClinicEnrollment(existing))return NextResponse.json({error:"Clinic Enrollment was added by another user. Reload this workflow to avoid overwriting it."},{status:409});
    const maximum=new Map<string,number>();for(const row of existing){const form=row.redcap_repeat_instrument,instance=Number(row.redcap_repeat_instance);if(form&&Number.isInteger(instance))maximum.set(form,Math.max(maximum.get(form)??0,instance));}const next=(form:string)=>String((maximum.get(form)??0)+1);
    const records:Values[]=[],base:Values={uic_ori:recordId};if(mode==="new"&&enrollment)Object.assign(base,copyAllowed(enrollment,enrollmentFields),clinicEnrollment?copyAllowed(clinicEnrollment,clinicEnrollmentFields):{});else if(includeClinicEnrollment&&clinicEnrollment)Object.assign(base,copyAllowed(clinicEnrollment,clinicEnrollmentFields));if(includeClientStatus&&clientStatus)Object.assign(base,copyAllowed(clientStatus,clientStatusFields));if(Object.keys(base).length>1)records.push(base);if(includeProfile&&profile)records.push({uic_ori:recordId,redcap_repeat_instrument:"hiv_treatment_profile",redcap_repeat_instance:next("hiv_treatment_profile"),...copyAllowed(profile,profileFields)});records.push({uic_ori:recordId,redcap_repeat_instrument:"clinic_visit",redcap_repeat_instance:next("clinic_visit"),...copyAllowed(visit,visitFields)});if(includePrepVisit&&prepVisit)records.push({uic_ori:recordId,redcap_repeat_instrument:"prep_visit",redcap_repeat_instance:next("prep_visit"),...copyAllowed(prepVisit,prepVisitFields)});if(includeMonitoring&&monitoring)records.push({uic_ori:recordId,redcap_repeat_instrument:"hiv_clinical_monitoring",redcap_repeat_instance:next("hiv_clinical_monitoring"),...copyAllowed(monitoring,monitoringFields)});
    const result=await redcap({content:"record",action:"import",format:"json",type:"flat",overwriteBehavior:"normal",forceAutoNumber:"false",dateFormat:"YMD",data:JSON.stringify(records),returnContent:"count",returnFormat:"json"});const activityLogged=await recordRedcapActivity({user,workflow:"clinic",recordId,staffName:visit.cnv_worker,serviceDate:visit.cnv_date,instrumentInstances:records.filter(row=>row.redcap_repeat_instrument).map(row=>({instrument:row.redcap_repeat_instrument,instance:Number(row.redcap_repeat_instance)})),submittedData:records});const queueCompleted=await completeQueueEntry(typeof input.queueId==="string"?input.queueId:undefined,recordId,user);return NextResponse.json({success:true,recordId,savedRows:records.length,activityLogged,queueCompleted,result});
  }catch(error){console.error("REDCap Clinic workflow import error:",error);return NextResponse.json({error:error instanceof Error?error.message:"Unable to save the Clinic workflow to REDCap."},{status:502});}
}
