"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, ChevronDown, Plus, RefreshCw, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";

type Patient = { record_id: string; uic: string; display_name: string; first_name: string; last_name: string; alias: string; phone: string; patient_code?: string };
type Entry = { id: string; queueDate: string; recordId?: string | null; displayName: string; alias?: string | null; patientCode?: string | null; phone?: string | null; source: string; isNewClient: boolean; status: string; currentStation: string; queueNumber?: number | null; checkedInAt?: string | null; tasks: string[]; appointmentSources: string[]; notes?: string | null; virtual: boolean };
const tasks = [["DOCTOR", "Doctor"], ["BLOOD_TEST", "Blood test"], ["MEDICATION", "Medication"], ["PREP", "PrEP"], ["ARV", "ARV"], ["OTHER", "Other"]] as const;
const stations = [["FILE_RETRIEVAL", "Retrieving file"], ["DOCTOR", "Doctor basket"], ["BLOOD_TEST", "Blood-test basket"], ["MEDICATION", "Medication"], ["CLINICIAN", "Clinician"]] as const;
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Indian/Mauritius", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());

export default function ClinicQueueBoard() {
  const [date, setDate] = useState(today()); const [entries, setEntries] = useState<Entry[]>([]); const [patients, setPatients] = useState<Patient[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [adding, setAdding] = useState(false);
  const [confirmReset, setConfirmReset] = useState(false); const [resetting, setResetting] = useState(false);
  const [clock, setClock] = useState(() => Date.now());
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Patient | null>(null); const [isNew, setIsNew] = useState(false); const [selectedProgramme, setSelectedProgramme] = useState(""); const [selectedTasks, setSelectedTasks] = useState<string[]>([]); const [firstQueue, setFirstQueue] = useState(""); const [notes, setNotes] = useState("");
  const load = async (quiet = false) => { if (!quiet) setLoading(true); setError(""); try { const response = await fetch(`/api/clinic-queue?date=${date}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw Error(data.error); setEntries(data); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load the queue."); } finally { setLoading(false); } };
  useEffect(() => { const initial = window.setTimeout(() => void load(), 0); const timer = window.setInterval(() => void load(true), 15000); return () => { window.clearTimeout(initial); window.clearInterval(timer); }; }, [date]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { fetch("/api/redcap/patients").then(async response => { const data = await response.json(); if (response.ok) setPatients(data); }).catch(() => undefined); }, []);
  useEffect(() => { const timer = window.setInterval(() => setClock(Date.now()), 30000); return () => window.clearInterval(timer); }, []);
  const matches = useMemo(() => { const q = query.trim().toLowerCase(); return q && !selected ? patients.filter(patient => patient.uic.toLowerCase().includes(q) || patient.display_name.toLowerCase().includes(q) || patient.alias.toLowerCase().includes(q)).slice(0, 8) : []; }, [patients, query, selected]);
  async function persist(payload: Record<string, unknown>) { const response = await fetch("/api/clinic-queue", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw Error(data.error); return data as Entry; }
  async function arrive(entry: Entry) { try { let current = entry; if (entry.virtual) current = await persist({ queueDate: date, recordId: entry.recordId, displayName: entry.displayName, alias: entry.alias, patientCode: entry.patientCode, phone: entry.phone, tasks: entry.tasks, source: "SCHEDULED", appointmentSources: entry.appointmentSources }); await patch(current.id, { status: "WAITING", currentStation: "FILE_RETRIEVAL" }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to check in the client."); } }
  async function patch(id: string, data: Record<string, unknown>) { const response = await fetch(`/api/clinic-queue/${encodeURIComponent(id)}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw Error(result.error); setEntries(current => current.map(entry => entry.id === id || (entry.virtual && entry.recordId === result.recordId) ? result : entry)); return result as Entry; }
  async function add() { const name = selected?.display_name || query.trim(); if (!name) return setError("Enter or select a client."); if (!selectedProgramme) return setError("Choose the walk-in programme."); if (!selectedTasks.length) return setError("Choose at least one visit purpose."); if (!firstQueue) return setError("Choose the first waiting queue."); try { await persist({ queueDate: date, recordId: selected?.uic, displayName: name, alias: selected?.alias, patientCode: selected?.patient_code, phone: selected?.phone, isNewClient: isNew, tasks: [selectedProgramme, ...selectedTasks], currentStation: firstQueue, notes }); setAdding(false); setQuery(""); setSelected(null); setIsNew(false); setSelectedProgramme(""); setSelectedTasks([]); setFirstQueue(""); setNotes(""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add the walk-in."); } }
  async function resetQueue() { setResetting(true); setError(""); try { const response = await fetch(`/api/clinic-queue?date=${encodeURIComponent(date)}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw Error(data.error); setConfirmReset(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to reset the queue."); } finally { setResetting(false); } }
  return <div className="clinic-queue-page mx-auto grid w-full max-w-6xl gap-5 px-4 sm:px-6">
    <header className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="dashboard-kicker">Live clinic operations</p><h1 className="text-3xl font-bold">Clinic Queue</h1><p className="mt-1 text-sm text-muted-foreground">Track the physical file and each service from arrival to clinical capture.</p></div><div className="clinic-queue-toolbar"><label><CalendarDays aria-hidden="true" /><span>Clinic date</span><Input aria-label="Clinic date" type="date" value={date} onChange={event => setDate(event.target.value)} /></label><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className={loading ? "animate-spin" : ""} /> Refresh</Button><Button onClick={() => setAdding(value => !value)}><Plus /> Add walk-in</Button></div></header>
    {error && <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
    {adding && <section className="outreach-card grid gap-4"><div><h2 className="text-xl font-bold">Add a walk-in</h2><p className="text-sm text-muted-foreground">Search for an existing client or enter a name for a new client, then record why they came.</p></div><div className="relative"><Input placeholder="UIC or name" value={query} onChange={event => { setQuery(event.target.value); setSelected(null); }} />{matches.length > 0 && <div className="absolute z-20 mt-1 w-full overflow-hidden rounded-xl border bg-card shadow-lg">{matches.map(patient => <button type="button" key={patient.uic} className="block w-full px-4 py-3 text-left hover:bg-muted" onClick={() => { setSelected(patient); setQuery(`${patient.uic} — ${patient.display_name}`); setIsNew(false); }}><strong>{patient.alias || patient.display_name}</strong><span className="ml-2 text-sm text-muted-foreground">{patient.uic} · {patient.display_name}</span></button>)}</div>}</div><label className="flex items-center gap-3"><Checkbox checked={isNew} onCheckedChange={checked => { setIsNew(Boolean(checked)); if (checked) setSelected(null); }} />New client</label><fieldset className="grid gap-2"><legend className="mb-2 text-sm font-bold">Programme</legend><div className="grid gap-2 sm:grid-cols-3">{[["PREP", "PrEP"], ["ARV", "ARV"], ["OTHER", "Other / new patient"]].map(([value, label]) => <label key={value} className="flex items-center gap-2 rounded-xl border px-3 py-2"><input type="radio" name="walk-in-programme" value={value} checked={selectedProgramme === value} onChange={() => setSelectedProgramme(value)} />{label}</label>)}</div></fieldset><fieldset className="grid gap-2"><legend className="mb-2 text-sm font-bold">Visit purpose</legend><div className="grid gap-2 sm:grid-cols-3">{[["BLOOD_TEST", "Blood test"], ["DOCTOR", "Doctor"], ["MEDICATION", "Medicine"]].map(([value, label]) => <label key={value} className="flex items-center gap-2 rounded-xl border px-3 py-2"><Checkbox checked={selectedTasks.includes(value)} onCheckedChange={checked => { const next = checked ? [...selectedTasks, value] : selectedTasks.filter(item => item !== value); setSelectedTasks(next); if (!next.includes(firstQueue)) setFirstQueue(next[0] ?? ""); }} />{label}</label>)}</div></fieldset><label className="outreach-field"><span>First waiting queue</span><select value={firstQueue} onChange={event => setFirstQueue(event.target.value)}><option value="">Choose…</option>{selectedTasks.map(task => <option key={task} value={task}>{task === "BLOOD_TEST" ? "Blood test" : task === "DOCTOR" ? "Doctor" : "Medicine"}</option>)}</select></label><Input placeholder="Notes (optional)" value={notes} onChange={event => setNotes(event.target.value)} /><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setAdding(false)}>Cancel</Button><Button onClick={() => void add()}>Add to waiting queue</Button></div></section>}
    <QueueSection status="EXPECTED" title="Expected today" subtitle="Appointments due today from REDCap" entries={entries} onArrive={arrive} onPatch={patch} />
    <WaitingQueues entries={entries.filter(entry => entry.status === "WAITING")} onPatch={patch} clock={clock} />
    <QueueSection status="READY" title="Ready for capture" subtitle="Returned to the clinician for ARV or PrEP capture" entries={entries} onArrive={arrive} onPatch={patch} />
    <QueueSection status="DONE" title="Done" subtitle="Clinical capture completed" entries={entries} onArrive={arrive} onPatch={patch} />
    <div className="flex justify-center border-t pt-5"><Button variant="outline" className="text-destructive" onClick={() => setConfirmReset(true)}><RotateCcw /> Reset queue</Button></div>
    {confirmReset && <div className="clinic-queue-modal" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget && !resetting) setConfirmReset(false); }}><section role="alertdialog" aria-modal="true" aria-labelledby="reset-queue-title" aria-describedby="reset-queue-description" className="clinic-queue-dialog"><h2 id="reset-queue-title" className="text-xl font-bold">Are you sure?</h2><p id="reset-queue-description" className="mt-2 text-sm text-muted-foreground">This will clear every queue update for {date}, including walk-ins and completed entries. Appointments due that day will be loaded from REDCap again under Expected today.</p><div className="mt-5 flex justify-end gap-2"><Button variant="outline" disabled={resetting} onClick={() => setConfirmReset(false)}>Cancel</Button><Button variant="destructive" disabled={resetting} onClick={() => void resetQueue()}>{resetting ? "Resetting…" : "Yes, reset queue"}</Button></div></section></div>}
  </div>;
}

function QueueSection({ status, title, subtitle, entries, onArrive, onPatch }: { status: string; title: string; subtitle: string; entries: Entry[]; onArrive: (entry: Entry) => void; onPatch: (id: string, data: Record<string, unknown>) => Promise<Entry> }) {
  const rows = entries.filter(entry => entry.status === status);
  return <section className={`clinic-queue-section clinic-queue-${status.toLowerCase()}`}><div className="flex items-center justify-between gap-3 border-b px-4 py-3"><div><h2 className="font-bold">{title}</h2><p className="text-xs text-muted-foreground">{subtitle}</p></div><span className="attendance-count">{rows.length}</span></div>{rows.length === 0 ? <p className="p-5 text-sm text-muted-foreground">No clients in this section.</p> : <div className="divide-y">{rows.map(entry => <QueueRow key={entry.id} entry={entry} onArrive={onArrive} onPatch={onPatch} />)}</div>}</section>;
}

function WaitingQueues({ entries, onPatch, clock }: { entries: Entry[]; onPatch: (id: string, data: Record<string, unknown>) => Promise<Entry>; clock: number }) {
  const assignedStations = new Set(["BLOOD_TEST", "DOCTOR", "MEDICATION"]);
  const retrieval = entries.filter(entry => !assignedStations.has(entry.currentStation));
  const baskets = [["BLOOD_TEST", "Blood test"], ["DOCTOR", "Doctor"], ["MEDICATION", "Medicine"]] as const;
  return <section className="clinic-queue-section clinic-queue-waiting"><div className="flex items-center justify-between gap-3 border-b px-4 py-3"><div><h2 className="font-bold">Waiting / in service</h2><p className="text-xs text-muted-foreground">Physical-file baskets for the three clinic queues</p></div><span className="attendance-count">{entries.length}</span></div>
    {retrieval.length > 0 && <div className="border-b bg-muted/40"><div className="px-4 pt-3 text-xs font-bold uppercase tracking-wide text-muted-foreground">File retrieval / assign a queue</div><div className="divide-y">{[...retrieval].sort(queueOrder).map(entry => <QueueRow key={entry.id} entry={entry} onArrive={() => undefined} onPatch={onPatch} clock={clock} />)}</div></div>}
    <div className="grid items-start gap-3 p-4 min-[560px]:grid-cols-3">{baskets.map(([station, title]) => { const rows = entries.filter(entry => entry.currentStation === station).sort(queueOrder); return <section key={station} className="min-w-0 overflow-hidden rounded-2xl border bg-card"><div className="flex items-center justify-between border-b bg-muted/50 px-3 py-2"><h3 className="font-bold">{title}</h3><span className="attendance-count">{rows.length}</span></div>{rows.length === 0 ? <p className="p-4 text-sm text-muted-foreground">No one waiting.</p> : <div className="divide-y">{rows.map(entry => <QueueRow key={entry.id} entry={entry} onArrive={() => undefined} onPatch={onPatch} clock={clock} />)}</div>}</section>; })}</div>
  </section>;
}

function queueOrder(a: Entry, b: Entry) { return (a.queueNumber ?? Number.MAX_SAFE_INTEGER) - (b.queueNumber ?? Number.MAX_SAFE_INTEGER); }

function QueueRow({ entry, onArrive, onPatch, clock }: { entry: Entry; onArrive: (entry: Entry) => void; onPatch: (id: string, data: Record<string, unknown>) => Promise<Entry>; clock?: number }) {
  const [open, setOpen] = useState(false); const labels = Object.fromEntries(tasks);
  const workflow = entry.tasks.includes("PREP") && !entry.tasks.includes("ARV") ? "prep" : "clinic";
  const workflowHref = `/clinic?queueId=${encodeURIComponent(entry.id)}${entry.recordId ? `&uic=${encodeURIComponent(entry.recordId)}` : "&new=1"}`;
  const minutesWaiting = entry.checkedInAt && clock ? Math.max(0, Math.floor((clock - new Date(entry.checkedInAt).getTime()) / 60000)) : 0;
  return <article className="p-4"><div className="flex flex-wrap items-center gap-3">{entry.status === "WAITING" && <div className="queue-number" aria-label={`Queue number ${entry.queueNumber ?? "not assigned"}, waiting ${minutesWaiting} minutes`}><strong>{entry.queueNumber ?? "—"}</strong><small>{minutesWaiting} min waiting</small></div>}<button type="button" className="min-w-0 flex-1 text-left" onClick={() => setOpen(value => !value)}><span className="block truncate font-bold">{entry.alias || entry.displayName}</span><span className="block text-sm text-muted-foreground">{entry.displayName}{entry.patientCode && <> · Patient code <strong className="text-red-600">{entry.patientCode}</strong></>}{entry.recordId ? ` · ${entry.recordId}` : " · New client"}</span></button><div className="flex flex-wrap gap-1">{entry.tasks.map(task => <span key={task} className="rounded-full bg-muted px-2 py-1 text-xs font-semibold">{labels[task] ?? task}</span>)}</div>{entry.status === "EXPECTED" && <Button size="sm" onClick={() => void onArrive(entry)}>Arrived</Button>}{entry.status === "WAITING" && <select aria-label="Current station" value={entry.currentStation} onChange={event => void onPatch(entry.id, { currentStation: event.target.value })}>{stations.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select>}{entry.status === "WAITING" && <Button size="sm" onClick={() => void onPatch(entry.id, { status: "READY", currentStation: "CLINICIAN" })}>Ready for capture</Button>}{entry.status === "READY" && <Link className="inline-flex min-h-8 items-center rounded-full bg-primary px-3 text-sm font-semibold text-primary-foreground" href={workflowHref}>Open {workflow === "prep" ? "PrEP" : "ARV"}</Link>}{entry.status === "DONE" && <Check className="text-primary" />}<button type="button" aria-label="Show details" onClick={() => setOpen(value => !value)}><ChevronDown className={open ? "rotate-180" : ""} /></button></div>{open && <div className="mt-3 grid gap-3 rounded-xl bg-muted/60 p-3 text-sm sm:grid-cols-3"><div><strong>Source</strong><br />{entry.source === "SCHEDULED" ? entry.appointmentSources.join(", ") || "Scheduled appointment" : "Walk-in"}</div><div><strong>Phone</strong><br />{entry.phone || "Not recorded"}</div><div><strong>Notes</strong><br />{entry.notes || "None"}</div>{entry.status !== "DONE" && <div className="sm:col-span-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => void onPatch(entry.id, { status: "EXPECTED", currentStation: "RECEPTION" })}>Return to expected</Button><Button size="sm" variant="outline" onClick={() => void onPatch(entry.id, { status: "DONE" })}>Mark done</Button></div>}</div>}</article>;
}
