"use client";

import { DobInput } from "@/components/DobInput";
import { numericAttributes, isRequiredField } from "@/lib/redcap-validation";

import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Values = Record<string, string>;
type Setter = (values: Values[]) => void;

const Field = ({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) => <label className="outreach-field"><span className={required ? "outreach-required" : undefined}>{label}</span>{children}</label>;
const Select = ({ value, onChange, children, required }: { value: string; onChange: (value: string) => void; children: React.ReactNode; required?: boolean }) => <select required={required} aria-required={required} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choose…</option>{children}</select>;
const YesNo = ({ value, onChange, required }: { value: string; onChange: (value: string) => void; required?: boolean }) => <Select required={required} value={value} onChange={onChange}><option value="1">Yes</option><option value="0">No</option></Select>;
const DateField = ({ value, onChange }: { value: string; onChange: (value: string) => void }) => <Input type="date" value={value} onChange={(event) => onChange(event.target.value)} />;
const gender = <><option value="1">Man</option><option value="2">Woman</option><option value="3">Transgender man</option><option value="4">Transgender woman</option><option value="5">Other</option><option value="9">Unknown / refuse</option></>;

const emptyPartner = (): Values => ({ itp_name: "", itp_nickname: "", itp_dob: "", itp_age: "", itp_gender: "", itp_description: "", itp_lives_with: "", itp_address: "", itp_work_address: "", itp_work_hours: "", itp_phone: "", itp_phone_alt: "", itp_relationship: "", itp_violence: "", itp_threats: "", itp_forced_sex: "", itp_notif_method: "", itp_notif_date: "", itp_1st_cont_date: "", itp_1st_cont_method: "", itp_2nd_cont_date: "", itp_2nd_cont_method: "", itp_3rd_cont_date: "", itp_3rd_cont_method: "", itp_contact_success: "", itp_contact_by_who: "", itp_contact_result: "", itp_contact_result_other: "", itp_hiv_result: "", itp_contact_art: "", itp_enrolled: "", itp_new_uic: "", itp_notes: "" });
const emptyChild = (): Values => ({ itch_name: "", itch_dob: "", itch_age: "", itch_gender: "", itch_address: "", itch_lives_with: "", itch_violence: "", itch_threats: "", itch_force_sex: "", itch_notif_method: "", itch_notif_date_limit: "", itch_contact_method: "", itch_hiv_result: "", itch_art: "", itch_enrolled: "", itch_new_uic: "", itch_notes: "" });

export function ReferralForms({ partners, setPartners, childReferrals, setChildren }: { partners: Values[]; setPartners: Setter; childReferrals: Values[]; setChildren: Setter }) {
  const update = (list: Values[], setter: Setter, index: number, key: string, value: string) => setter(list.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const remove = (list: Values[], setter: Setter, index: number) => setter(list.filter((_, itemIndex) => itemIndex !== index));
  const input = (list: Values[], setter: Setter, index: number, key: string, type = "text") => <Input required={isRequiredField(key)} aria-required={isRequiredField(key)} type={type} {...numericAttributes(key)} value={list[index][key]} onChange={(event) => update(list, setter, index, key, event.target.value)} />;
  const select = (list: Values[], setter: Setter, index: number, key: string, options: [string, string][]) => <Select required={isRequiredField(key)} value={list[index][key]} onChange={(value) => update(list, setter, index, key, value)}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select>;
  const yesNo = (list: Values[], setter: Setter, index: number, key: string) => <YesNo required={isRequiredField(key)} value={list[index][key]} onChange={(value) => update(list, setter, index, key, value)} />;
  const partnerCard = (v: Values, index: number) => <article key={index} className="rounded-2xl border p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">Partner {index + 1}</h3><Button variant="ghost" size="icon" aria-label="Remove partner" onClick={() => remove(partners, setPartners, index)}><Trash2 /></Button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Partner name" required>{input(partners, setPartners, index, "itp_name")}</Field><Field label="Nickname / alias">{input(partners, setPartners, index, "itp_nickname")}</Field><Field label="Partner date of birth"><DobInput value={v.itp_dob} onChange={(value) => update(partners, setPartners, index, "itp_dob", value)} /></Field><Field label="Partner age if DOB unknown">{input(partners, setPartners, index, "itp_age", "number")}</Field><Field label="Partner gender" required><Select required value={v.itp_gender} onChange={(value) => update(partners, setPartners, index, "itp_gender", value)}>{gender}</Select></Field><Field label="Lives with index client?">{select(partners, setPartners, index, "itp_lives_with", [["1","Yes"],["2","No"],["3","Refuse to answer"]])}</Field><Field label="Physical description"><textarea value={v.itp_description} onChange={(event) => update(partners, setPartners, index, "itp_description", event.target.value)} /></Field>{v.itp_lives_with === "2" && <Field label="Address / landmarks"><textarea value={v.itp_address} onChange={(event) => update(partners, setPartners, index, "itp_address", event.target.value)} /></Field>}<Field label="Work address"><textarea value={v.itp_work_address} onChange={(event) => update(partners, setPartners, index, "itp_work_address", event.target.value)} /></Field><Field label="Work hours">{input(partners, setPartners, index, "itp_work_hours")}</Field><Field label="Phone number">{input(partners, setPartners, index, "itp_phone", "tel")}</Field><Field label="Alternative phone number">{input(partners, setPartners, index, "itp_phone_alt", "tel")}</Field><Field label="Relationship to index client">{select(partners, setPartners, index, "itp_relationship", [["1","Spouse/life partner"],["2","Girlfriend/boyfriend"],["3","Sex partner for fun"],["4","Pays index client for sex"],["5","Index client pays for sex"],["99","Other"]])}</Field></div><ReferralFollowUp kind="partner" values={v} list={partners} setter={setPartners} index={index} update={update} select={select} yesNo={yesNo} input={input} /></article>;
  const childCard = (v: Values, index: number) => <article key={index} className="rounded-2xl border p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">Child {index + 1}</h3><Button variant="ghost" size="icon" aria-label="Remove child" onClick={() => remove(childReferrals, setChildren, index)}><Trash2 /></Button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Child name">{input(childReferrals, setChildren, index, "itch_name")}</Field><Field label="Child date of birth"><DobInput value={v.itch_dob} onChange={(value) => update(childReferrals, setChildren, index, "itch_dob", value)} /></Field><Field label="Child age if DOB unknown">{input(childReferrals, setChildren, index, "itch_age", "number")}</Field><Field label="Child gender"><Select value={v.itch_gender} onChange={(value) => update(childReferrals, setChildren, index, "itch_gender", value)}>{gender}</Select></Field><Field label="Address / landmarks"><textarea value={v.itch_address} onChange={(event) => update(childReferrals, setChildren, index, "itch_address", event.target.value)} /></Field><Field label="Lives with index client?">{select(childReferrals, setChildren, index, "itch_lives_with", [["1","Yes"],["2","No"],["3","Refuse to answer"]])}</Field></div><ReferralFollowUp kind="child" values={v} list={childReferrals} setter={setChildren} index={index} update={update} select={select} yesNo={yesNo} input={input} /></article>;
  return <section className="outreach-card grid gap-6"><div><h2 className="text-xl font-bold">Partner services</h2><p className="text-sm text-muted-foreground">Adding a referral is optional. Fields marked * are required for each referral added. Complete safety screening before notification.</p></div><div className="grid gap-3">{partners.map(partnerCard)}<Button variant="outline" onClick={() => setPartners([...partners, emptyPartner()])}><Plus />Add partner</Button></div><div className="grid gap-3">{childReferrals.map(childCard)}<Button variant="outline" onClick={() => setChildren([...childReferrals, emptyChild()])}><Plus />Add child</Button></div></section>;
}

function ReferralFollowUp({ kind, values: v, list, setter, index, update, select, yesNo, input }: { kind: "partner" | "child"; values: Values; list: Values[]; setter: Setter; index: number; update: (list: Values[], setter: Setter, index: number, key: string, value: string) => void; select: (list: Values[], setter: Setter, index: number, key: string, options: [string, string][]) => React.ReactNode; yesNo: (list: Values[], setter: Setter, index: number, key: string) => React.ReactNode; input: (list: Values[], setter: Setter, index: number, key: string, type?: string) => React.ReactNode }) {
  const child = kind === "child";
  const key = (partnerKey: string, childKey: string) => child ? childKey : partnerKey;
  const notification: [string, string][] = child ? [["1","Contract agreement referral"],["2","Community based testing"],["3","Facility based testing"],["4","Testing not recommended — security"],["5","Testing not required — known case"]] : [["1","Provider referral"],["2","Contract agreement referral"],["3","Dual referral"],["4","Client referral"],["5","Not recommended — security"],["6","Not required — known case"]];
  const needsLimit = child ? v.itch_notif_method === "1" : ["2", "3"].includes(v.itp_notif_method);
  return <><details open className="mt-4 rounded-2xl border p-4"><summary className="cursor-pointer font-bold">Intimate Partner Violence</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Physical violence" required>{yesNo(list, setter, index, key("itp_violence", "itch_violence"))}</Field><Field label="Threats of violence" required>{yesNo(list, setter, index, key("itp_threats", "itch_threats"))}</Field><Field label="Forced sexual activity" required>{yesNo(list, setter, index, key("itp_forced_sex", "itch_force_sex"))}</Field></div></details><details open className="mt-4 rounded-2xl border p-4"><summary className="cursor-pointer font-bold">Notification Method</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Preferred notification method" required>{select(list, setter, index, key("itp_notif_method", "itch_notif_method"), notification)}</Field>{needsLimit && <Field label="Limit date"><Input value={v[key("itp_notif_date", "itch_notif_date_limit")]} onChange={(event) => update(list, setter, index, key("itp_notif_date", "itch_notif_date_limit"), event.target.value)} /></Field>}</div></details><details className="mt-4 rounded-2xl border p-4"><summary className="cursor-pointer font-bold">Result / Follow-up</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{child ? <><Field label="Contact method">{select(list, setter, index, "itch_contact_method", [["1","Community based"],["2","Facility"],["3","Contract agreement"]])}</Field><Field label="HIV status">{select(list, setter, index, "itch_hiv_result", [["1","HIV positive"],["2","HIV negative"]])}</Field>{v.itch_hiv_result === "1" && <Field label="On ART treatment">{yesNo(list, setter, index, "itch_art")}</Field>}</> : <PartnerResults values={v} list={list} setter={setter} index={index} update={update} select={select} yesNo={yesNo} />}</div></details><details className="mt-4 rounded-2xl border p-4"><summary className="cursor-pointer font-bold">PILS / Administrative</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label={child ? "Child subsequently enrolled as PILS client?" : "Partner subsequently enrolled as PILS client?"}>{yesNo(list, setter, index, key("itp_enrolled", "itch_enrolled"))}</Field>{v[key("itp_enrolled", "itch_enrolled")] === "1" && <Field label={child ? "Child client UIC if enrolled" : "Partner client UIC if enrolled"}>{input(list, setter, index, key("itp_new_uic", "itch_new_uic"))}</Field>}<Field label={child ? "Child follow-up notes" : "Partner follow-up notes"}><textarea value={v[key("itp_notes", "itch_notes")]} onChange={(event) => update(list, setter, index, key("itp_notes", "itch_notes"), event.target.value)} /></Field></div></details></>;
}

function PartnerResults({ values: v, list, setter, index, update, select, yesNo }: { values: Values; list: Values[]; setter: Setter; index: number; update: (list: Values[], setter: Setter, index: number, key: string, value: string) => void; select: (list: Values[], setter: Setter, index: number, key: string, options: [string, string][]) => React.ReactNode; yesNo: (list: Values[], setter: Setter, index: number, key: string) => React.ReactNode }) {
  const date = (key: string) => <DateField value={v[key]} onChange={(value) => update(list, setter, index, key, value)} />;
  return <><Field label="First contact date">{date("itp_1st_cont_date")}</Field><Field label="Contact method">{select(list, setter, index, "itp_1st_cont_method", [["1","Phone"],["2","Face to face"]])}</Field><Field label="Second contact date">{date("itp_2nd_cont_date")}</Field><Field label="Contact method">{select(list, setter, index, "itp_2nd_cont_method", [["1","Phone"],["2","Face to face"]])}</Field><Field label="Third contact date">{date("itp_3rd_cont_date")}</Field><Field label="Contact method">{select(list, setter, index, "itp_3rd_cont_method", [["1","Phone"],["2","Face to face"]])}</Field><Field label="Successful contact">{yesNo(list, setter, index, "itp_contact_success")}</Field>{v.itp_contact_success === "1" && <><Field label="Who made contact">{select(list, setter, index, "itp_contact_by_who", [["1","Client"],["2","Service provider"],["3","Client + service provider"]])}</Field><Field label="Contact result">{select(list, setter, index, "itp_contact_result", [["1","Partner did HIV test"],["2","Partner refused HIV test"],["3","Partner is known HIV case"],["4","Other"]])}</Field>{v.itp_contact_result === "4" && <Field label="Other contact result"><Input value={v.itp_contact_result_other} onChange={(event) => update(list, setter, index, "itp_contact_result_other", event.target.value)} /></Field>}{v.itp_contact_result === "1" && <Field label="HIV status (if tested)">{select(list, setter, index, "itp_hiv_result", [["1","HIV positive"],["2","HIV negative"]])}</Field>}{(v.itp_hiv_result === "1" || v.itp_contact_result === "3") && <Field label="On ART treatment">{yesNo(list, setter, index, "itp_contact_art")}</Field>}</>}</>;
}
