"use client";

import { DobInput } from "@/components/DobInput";
import { numericAttributes, isRequiredField } from "@/lib/redcap-validation";

import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Values = Record<string, string>;
type Setter = (values: Values[]) => void;

const Field = ({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) => <label className="outreach-field"><span className={required ? "outreach-required" : undefined}>{label}</span>{children}</label>;
const Select = ({ value, onChange, children, required }: { value: string; onChange: (value: string) => void; children: React.ReactNode; required?: boolean }) => <select required={required} aria-required={required} value={value} onChange={(event) => onChange(event.target.value)}><option value="">Choose…</option>{children}</select>;
const YesNo = ({ value, onChange, required }: { value: string; onChange: (value: string) => void; required?: boolean }) => <Select required={required} value={value} onChange={onChange}><option value="1">Yes</option><option value="0">No</option></Select>;
const DateField = ({ value, onChange }: { value: string; onChange: (value: string) => void }) => <Input type="date" value={value} onChange={(event) => onChange(event.target.value)} />;
const gender = <><option value="1">Man</option><option value="2">Woman</option><option value="3">Transgender man</option><option value="4">Transgender woman</option><option value="5">Other</option><option value="9">Unknown / refuse</option></>;

const emptyPartner = (): Values => ({ partner_name: "", partner_nickname: "", partner_dob: "", partner_age: "", partner_gender: "", partner_description: "", partner_lives_with: "", partner_address: "", partner_address_2: "", partner_work_hours: "", partner_phone: "", partner_phone_alt: "", partner_relationship: "", partner_violence: "", partner_threats: "", partner_forced_sex: "", part_not_method: "", part_not_date: "", first_cont_date: "", first_cont_method: "", second_cont_date: "", first_cont_method_2: "", third_cont_date: "", first_cont_method_3: "", part_cont_success: "", part_cont_by_who: "", contact_result: "", cont_result_other: "", part_hiv_result: "", part_cont_art: "", partner_enrolled: "", partner_new_uic: "", partner_notes: "" });
const emptyChild = (): Values => ({ child_nameprc: "", child_dobprc: "", child_ageprc: "", child_genderprc: "", partner_addressprc: "", partner_lives_withprc: "", partner_violenceprc: "", partner_threatsprc: "", partner_forced_sexprc: "", part_not_methodprc: "", part_not_dateprc: "", first_cont_methodprc: "", part_hiv_resultprc: "", part_cont_artprc: "", child_enrolledprc: "", child_new_uicprc: "", child_notesprc: "" });

export function ReferralForms({ partners, setPartners, childReferrals, setChildren }: { partners: Values[]; setPartners: Setter; childReferrals: Values[]; setChildren: Setter }) {
  const update = (list: Values[], setter: Setter, index: number, key: string, value: string) => setter(list.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item));
  const remove = (list: Values[], setter: Setter, index: number) => setter(list.filter((_, itemIndex) => itemIndex !== index));
  const input = (list: Values[], setter: Setter, index: number, key: string, type = "text") => <Input required={isRequiredField(key)} aria-required={isRequiredField(key)} type={type} {...numericAttributes(key)} value={list[index][key]} onChange={(event) => update(list, setter, index, key, event.target.value)} />;
  const select = (list: Values[], setter: Setter, index: number, key: string, options: [string, string][]) => <Select required={isRequiredField(key)} value={list[index][key]} onChange={(value) => update(list, setter, index, key, value)}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select>;
  const yesNo = (list: Values[], setter: Setter, index: number, key: string) => <YesNo required={isRequiredField(key)} value={list[index][key]} onChange={(value) => update(list, setter, index, key, value)} />;
  const partnerCard = (v: Values, index: number) => <article key={index} className="rounded-2xl border p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">Partner {index + 1}</h3><Button variant="ghost" size="icon" aria-label="Remove partner" onClick={() => remove(partners, setPartners, index)}><Trash2 /></Button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Partner name" required>{input(partners, setPartners, index, "partner_name")}</Field><Field label="Nickname / alias">{input(partners, setPartners, index, "partner_nickname")}</Field><Field label="Partner date of birth"><DobInput value={v.partner_dob} onChange={(value) => update(partners, setPartners, index, "partner_dob", value)} /></Field><Field label="Partner age if DOB unknown">{input(partners, setPartners, index, "partner_age", "number")}</Field><Field label="Partner gender" required><Select required value={v.partner_gender} onChange={(value) => update(partners, setPartners, index, "partner_gender", value)}>{gender}</Select></Field><Field label="Lives with index client?">{select(partners, setPartners, index, "partner_lives_with", [["1","Yes"],["2","No"],["3","Refuse to answer"]])}</Field><Field label="Physical description"><textarea value={v.partner_description} onChange={(event) => update(partners, setPartners, index, "partner_description", event.target.value)} /></Field>{v.partner_lives_with === "2" && <Field label="Address / landmarks"><textarea value={v.partner_address} onChange={(event) => update(partners, setPartners, index, "partner_address", event.target.value)} /></Field>}<Field label="Work address"><textarea value={v.partner_address_2} onChange={(event) => update(partners, setPartners, index, "partner_address_2", event.target.value)} /></Field><Field label="Work hours">{input(partners, setPartners, index, "partner_work_hours")}</Field><Field label="Phone number">{input(partners, setPartners, index, "partner_phone", "tel")}</Field><Field label="Alternative phone number">{input(partners, setPartners, index, "partner_phone_alt", "tel")}</Field><Field label="Relationship to index client">{select(partners, setPartners, index, "partner_relationship", [["1","Spouse/life partner"],["2","Girlfriend/boyfriend"],["3","Sex partner for fun"],["4","Pays index client for sex"],["5","Index client pays for sex"],["99","Other"]])}</Field></div><ReferralFollowUp kind="partner" values={v} list={partners} setter={setPartners} index={index} update={update} select={select} yesNo={yesNo} input={input} /></article>;
  const childCard = (v: Values, index: number) => <article key={index} className="rounded-2xl border p-4"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">Child {index + 1}</h3><Button variant="ghost" size="icon" aria-label="Remove child" onClick={() => remove(childReferrals, setChildren, index)}><Trash2 /></Button></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Child name">{input(childReferrals, setChildren, index, "child_nameprc")}</Field><Field label="Child date of birth"><DobInput value={v.child_dobprc} onChange={(value) => update(childReferrals, setChildren, index, "child_dobprc", value)} /></Field><Field label="Child age if DOB unknown">{input(childReferrals, setChildren, index, "child_ageprc", "number")}</Field><Field label="Child gender"><Select value={v.child_genderprc} onChange={(value) => update(childReferrals, setChildren, index, "child_genderprc", value)}>{gender}</Select></Field><Field label="Address / landmarks"><textarea value={v.partner_addressprc} onChange={(event) => update(childReferrals, setChildren, index, "partner_addressprc", event.target.value)} /></Field><Field label="Lives with index client?">{select(childReferrals, setChildren, index, "partner_lives_withprc", [["1","Yes"],["2","No"],["3","Refuse to answer"]])}</Field></div><ReferralFollowUp kind="child" values={v} list={childReferrals} setter={setChildren} index={index} update={update} select={select} yesNo={yesNo} input={input} /></article>;
  return <section className="outreach-card grid gap-6"><div><h2 className="text-xl font-bold">Partner services</h2><p className="text-sm text-muted-foreground">Adding a referral is optional. Fields marked * are required for each referral added. Complete safety screening before notification.</p></div><div className="grid gap-3">{partners.map(partnerCard)}<Button variant="outline" onClick={() => setPartners([...partners, emptyPartner()])}><Plus />Add partner</Button></div><div className="grid gap-3">{childReferrals.map(childCard)}<Button variant="outline" onClick={() => setChildren([...childReferrals, emptyChild()])}><Plus />Add child</Button></div></section>;
}

function ReferralFollowUp({ kind, values: v, list, setter, index, update, select, yesNo, input }: { kind: "partner" | "child"; values: Values; list: Values[]; setter: Setter; index: number; update: (list: Values[], setter: Setter, index: number, key: string, value: string) => void; select: (list: Values[], setter: Setter, index: number, key: string, options: [string, string][]) => React.ReactNode; yesNo: (list: Values[], setter: Setter, index: number, key: string) => React.ReactNode; input: (list: Values[], setter: Setter, index: number, key: string, type?: string) => React.ReactNode }) {
  const child = kind === "child";
  const key = (partnerKey: string, childKey: string) => child ? childKey : partnerKey;
  const notification: [string, string][] = child ? [["1","Contract agreement referral"],["2","Community based testing"],["3","Facility based testing"],["4","Testing not recommended — security"],["5","Testing not required — known case"]] : [["1","Provider referral"],["2","Contract agreement referral"],["3","Dual referral"],["4","Client referral"],["5","Not recommended — security"],["6","Not required — known case"]];
  const needsLimit = child ? v.part_not_methodprc === "1" : ["2", "3"].includes(v.part_not_method);
  return <><details open className="mt-4 rounded-2xl border p-4"><summary className="cursor-pointer font-bold">Intimate Partner Violence</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Physical violence" required>{yesNo(list, setter, index, key("partner_violence", "partner_violenceprc"))}</Field><Field label="Threats of violence" required>{yesNo(list, setter, index, key("partner_threats", "partner_threatsprc"))}</Field><Field label="Forced sexual activity" required>{yesNo(list, setter, index, key("partner_forced_sex", "partner_forced_sexprc"))}</Field></div></details><details open className="mt-4 rounded-2xl border p-4"><summary className="cursor-pointer font-bold">Notification Method</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Preferred notification method" required>{select(list, setter, index, key("part_not_method", "part_not_methodprc"), notification)}</Field>{needsLimit && <Field label="Limit date"><Input value={v[key("part_not_date", "part_not_dateprc")]} onChange={(event) => update(list, setter, index, key("part_not_date", "part_not_dateprc"), event.target.value)} /></Field>}</div></details><details className="mt-4 rounded-2xl border p-4"><summary className="cursor-pointer font-bold">Result / Follow-up</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{child ? <><Field label="Contact method">{select(list, setter, index, "first_cont_methodprc", [["1","Community based"],["2","Facility"],["3","Contract agreement"]])}</Field><Field label="HIV status">{select(list, setter, index, "part_hiv_resultprc", [["1","HIV positive"],["2","HIV negative"]])}</Field>{v.part_hiv_resultprc === "1" && <Field label="On ART treatment">{yesNo(list, setter, index, "part_cont_artprc")}</Field>}</> : <PartnerResults values={v} list={list} setter={setter} index={index} update={update} select={select} yesNo={yesNo} />}</div></details><details className="mt-4 rounded-2xl border p-4"><summary className="cursor-pointer font-bold">PILS / Administrative</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label={child ? "Child subsequently enrolled as PILS client?" : "Partner subsequently enrolled as PILS client?"}>{yesNo(list, setter, index, key("partner_enrolled", "child_enrolledprc"))}</Field>{v[key("partner_enrolled", "child_enrolledprc")] === "1" && <Field label={child ? "Child client UIC if enrolled" : "Partner client UIC if enrolled"}>{input(list, setter, index, key("partner_new_uic", "child_new_uicprc"))}</Field>}<Field label={child ? "Child follow-up notes" : "Partner follow-up notes"}><textarea value={v[key("partner_notes", "child_notesprc")]} onChange={(event) => update(list, setter, index, key("partner_notes", "child_notesprc"), event.target.value)} /></Field></div></details></>;
}

function PartnerResults({ values: v, list, setter, index, update, select, yesNo }: { values: Values; list: Values[]; setter: Setter; index: number; update: (list: Values[], setter: Setter, index: number, key: string, value: string) => void; select: (list: Values[], setter: Setter, index: number, key: string, options: [string, string][]) => React.ReactNode; yesNo: (list: Values[], setter: Setter, index: number, key: string) => React.ReactNode }) {
  const date = (key: string) => <DateField value={v[key]} onChange={(value) => update(list, setter, index, key, value)} />;
  return <><Field label="First contact date">{date("first_cont_date")}</Field><Field label="Contact method">{select(list, setter, index, "first_cont_method", [["1","Phone"],["2","Face to face"]])}</Field><Field label="Second contact date">{date("second_cont_date")}</Field><Field label="Contact method">{select(list, setter, index, "first_cont_method_2", [["1","Phone"],["2","Face to face"]])}</Field><Field label="Third contact date">{date("third_cont_date")}</Field><Field label="Contact method">{select(list, setter, index, "first_cont_method_3", [["1","Phone"],["2","Face to face"]])}</Field><Field label="Successful contact">{yesNo(list, setter, index, "part_cont_success")}</Field>{v.part_cont_success === "1" && <><Field label="Who made contact">{select(list, setter, index, "part_cont_by_who", [["1","Client"],["2","Service provider"],["3","Client + service provider"]])}</Field><Field label="Contact result">{select(list, setter, index, "contact_result", [["1","Partner did HIV test"],["2","Partner refused HIV test"],["3","Partner is known HIV case"],["4","Other"]])}</Field>{v.contact_result === "4" && <Field label="Other contact result"><Input value={v.cont_result_other} onChange={(event) => update(list, setter, index, "cont_result_other", event.target.value)} /></Field>}{v.contact_result === "1" && <Field label="HIV status (if tested)">{select(list, setter, index, "part_hiv_result", [["1","HIV positive"],["2","HIV negative"]])}</Field>}{(v.part_hiv_result === "1" || v.contact_result === "3") && <Field label="On ART treatment">{yesNo(list, setter, index, "part_cont_art")}</Field>}</>}</>;
}
