import Link from "next/link";
import { approveUserAction, rejectUserAction } from "@/app/auth-actions";
import { requireAdmin, userRoles } from "@/lib/auth";
import { ORGANIZATIONS, Organization, USER_ROLES, UserRole } from "@/lib/auth-types";
import { db } from "@/lib/db";

export default async function AdminUsersPage() {
  await requireAdmin();
  const [pending, active, inactive] = await Promise.all([
    db.user.findMany({ where: { status: "PENDING" }, orderBy: { createdAt: "asc" } }),
    db.user.findMany({ where: { status: "APPROVED" }, orderBy: { name: "asc" } }),
    db.user.findMany({ where: { status: { in: ["REJECTED", "SUSPENDED"] } }, orderBy: { name: "asc" } }),
  ]);
  return <main className="admin-page"><div className="admin-heading"><div><p className="pils-eyebrow inline-block">Administration</p><h1>User approvals</h1><p>Review new registrations and assign the role they will use.</p></div><Link className="auth-button" href="/outreach">Back to app</Link></div><section className="admin-card"><h2>Pending approval ({pending.length})</h2>{pending.length === 0 ? <p>No registrations are waiting.</p> : <div className="admin-user-list">{pending.map((user) => <article key={user.id} className="admin-user"><div><strong>{user.name}</strong><p>@{user.username} · {ORGANIZATIONS[user.organization as Organization] ?? user.organization}</p><p>Requested role: {USER_ROLES[user.requestedRole as UserRole] ?? user.requestedRole}</p><small>Registered {user.createdAt.toLocaleDateString("en-GB")}</small></div><form action={approveUserAction}><input type="hidden" name="userId" value={user.id} /><label>Approved role<select name="role" defaultValue={user.requestedRole}>{Object.entries(USER_ROLES).map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select></label><button className="auth-button" type="submit">Approve</button></form><form action={rejectUserAction}><input type="hidden" name="userId" value={user.id} /><button className="auth-button auth-button-secondary" type="submit">Reject</button></form><Link className="auth-button auth-button-secondary" href={`/admin/users/${user.id}`}>Manage</Link></article>)}</div>}</section><section className="admin-card"><h2>Active users ({active.length})</h2><div className="admin-user-list">{active.map((user) => <article key={user.id} className="admin-user"><div><strong>{user.name}</strong><p>@{user.username} · {ORGANIZATIONS[user.organization as Organization] ?? user.organization}</p></div><span className="pils-eyebrow">{userRoles(user).map(role => USER_ROLES[role as UserRole] ?? role).join(" · ")}</span><Link className="auth-button auth-button-secondary" href={`/admin/users/${user.id}`}>Manage</Link></article>)}</div></section>{inactive.length > 0 && <section className="admin-card"><h2>Inactive users ({inactive.length})</h2><div className="admin-user-list">{inactive.map((user) => <article key={user.id} className="admin-user"><div><strong>{user.name}</strong><p>@{user.username} · {ORGANIZATIONS[user.organization as Organization] ?? user.organization}</p></div><span className="pils-eyebrow">{user.status === "SUSPENDED" ? "Suspended" : "Rejected"}</span><Link className="auth-button auth-button-secondary" href={`/admin/users/${user.id}`}>Manage</Link></article>)}</div></section>}</main>;
}
